### ISSUE TITLE
The prop `inputRef` is marked as required in `InputTrigger`, but its value is `undefined`

### ISSUE THREAD

**Issue by vferreir42** [abinavseelan/react-input-trigger#18]
Code : 

`<InputTrigger
    trigger={{
        keyCode: 50,
        shiftKey: true,
    }}
    >
    <textarea />
</InputTrigger> `

When i press '@' key i have automatically the following error : "this.props.inputRef is not a function"

**Comment by mitchellbusby** [comment]
I am having this problem too - I think that the maintainer has accidentally published a prerelease version of the package as the latest. Try specifying the version to be installing (the version in this repo is 1.1.2, the latest in npm is 2.0.0-beta-1)

**Comment by rheaditi** [comment]
> I am having this problem too - I think that the maintainer has accidentally published a prerelease version of the package as the latest. Try specifying the version to be installing (the version in this repo is 1.1.2, the latest in npm is 2.0.0-beta-1)

Sorry for the confusion @mitchellbusby @vferreir42
We've updated the `latest` tag to reflect `1.1.2`.

**Comment by mitchellbusby** [comment]
Awesome! Thanks @rheaditi (I'm guessing this can be closed now?)
